name: Node Github CI

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    
    
    - name: Build and Package Website
      run: git clone https://github.com/daimonas13/node-test.git
    - name: Install Octopus CLI
      run: |

        sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https && \
        curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - && \
        sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" && \
        sudo apt update && sudo apt install octopuscli
        sudo apt update && sudo apt install git

    # A file, directory or wildcard pattern that describes what to upload

    
    - name: Upload
 
      run: |
        
    
        octo pack --id="Andreas-test" --format="Zip" --basePath="./node-test" --outFolder="./packages"
        
    - name: Push Andreas-test to Octopus
      run: octo push --package="./packages/Andreas-test.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUS_SERVER_URL }}" --apiKey="${{ secrets.OCTOPUS_API_KEY }}"
      


       

      
    
